### ISSUE TITLE
Ensure all normalized values are translated to Arabic

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#699] opened 2021-06-11 15:33 UTC
As the DLME data manager, I need to ensure that all normalized fields that should be translated to Arabic actually are. When values are normalized in English, they must be translated through a translation map to fetch equivalent Arabic values. If a value is not found in the Arabic translation map, nothing is returned and no warning is raised. 

Consult the [field notes](https://docs.google.com/document/d/1rgm6CYGiPvOjvNp9e4B0Nsk_RAGD04CShrAb9h4shcM/edit) to see which fields are translated

Requirements:

- Fails if length of normalized 'en' values array does not match length of normalized 'ar-Arab' values array.
- Prints error message to terminal including both language keys and arrays, stops processing

**Comment by aaron-collier** [comment] 2021-06-30 21:18
Closing as duplicate of #704

**Closed by aaron-collier** 2021-06-30 21:18 UTC
Labels: infrastructure
